/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLoginForm: typeof import('./src/components/auth/AuthLoginForm.vue')['default']
    AuthModal: typeof import('./src/components/global/AuthModal.vue')['default']
    AuthRescueForm: typeof import('./src/components/auth/AuthRescueForm.vue')['default']
    AuthSignupForm: typeof import('./src/components/auth/AuthSignupForm.vue')['default']
    CButton: typeof import('./src/components/ui/CButton.vue')['default']
    CContextMenu: typeof import('./src/components/ui/CContextMenu.vue')['default']
    CGroup: typeof import('./src/components/ui/CGroup.vue')['default']
    ComplexArrayBuilder: typeof import('./src/components/ui/ComplexArrayBuilder.vue')['default']
    ComplexArrayParams: typeof import('./src/components/ui/ComplexArrayParams.vue')['default']
    ComponentFormWrapper: typeof import('./src/components/modules/ComponentFormWrapper.vue')['default']
    ComponentGamepad: typeof import('./src/components/modules/ComponentGamepad.vue')['default']
    ComponentHeader: typeof import('./src/components/modules/ComponentHeader.vue')['default']
    ComponentLoadSessions: typeof import('./src/components/modules/ComponentLoadSessions.vue')['default']
    ComponentNode: typeof import('./src/components/modules/ComponentNode.vue')['default']
    ComponentQuickEditPanel: typeof import('./src/components/modules/ComponentQuickEditPanel.vue')['default']
    ContextMenu: typeof import('./src/components/ui/ContextMenu.vue')['default']
    ExpressionBuilder: typeof import('./src/components/ui/ExpressionBuilder.vue')['default']
    FeaturedGameCard: typeof import('./src/components/ui/FeaturedGameCard.vue')['default']
    GameCard: typeof import('./src/components/ui/GameCard.vue')['default']
    GlobalOverlays: typeof import('./src/components/global/GlobalOverlays.vue')['default']
    IconRender: typeof import('./src/components/ui/IconRender.vue')['default']
    Logo: typeof import('./src/components/ui/Logo.vue')['default']
    Node: typeof import('./src/components/ui/Node.vue')['default']
    ProjectCard: typeof import('./src/components/ui/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VPasswordField: typeof import('./src/components/ui/VPasswordField.vue')['default']
  }
}
