/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockCatalog: typeof import('./src/components/modules/BlockCatalog.vue')['default']
    CodeDrawer: typeof import('./src/components/modules/CodeDrawer.vue')['default']
    ComplexArrayBuilder: typeof import('./src/components/ui/ComplexArrayBuilder.vue')['default']
    ComponentFormWrapper: typeof import('./src/components/modules/ComponentFormWrapper.vue')['default']
    ComponentLoadSessions: typeof import('./src/components/modules/ComponentLoadSessions.vue')['default']
    ComponentNode: typeof import('./src/components/modules/ComponentNode.vue')['default']
    ComponentQuickEditPanel: typeof import('./src/components/modules/ComponentQuickEditPanel.vue')['default']
    ConnectionStatusTag: typeof import('./src/components/modules/ConnectionStatusTag.vue')['default']
    CreateNodeMenu: typeof import('./src/components/modules/CreateNodeMenu.vue')['default']
    CreateObjectDialog: typeof import('./src/components/modules/CreateObjectDialog.vue')['default']
    DialogSettings: typeof import('./src/components/modules/DialogSettings.vue')['default']
    DiscreteSetup: typeof import('./src/components/ui/DiscreteSetup.vue')['default']
    ExplorerPanel: typeof import('./src/components/modules/ExplorerPanel.vue')['default']
    ExplorerRail: typeof import('./src/components/modules/ExplorerRail.vue')['default']
    ExpressionBuilder: typeof import('./src/components/ui/ExpressionBuilder.vue')['default']
    GlobalSearch: typeof import('./src/components/modules/GlobalSearch.vue')['default']
    Logo: typeof import('./src/components/ui/Logo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    Node: typeof import('./src/components/ui/Node.vue')['default']
    ProjectCard: typeof import('./src/components/modules/ProjectCard.vue')['default']
    Properties: typeof import('./src/components/modules/Properties.vue')['default']
    RecentProjectsOverlay: typeof import('./src/components/modules/RecentProjectsOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
