/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CButton: typeof import('./src/components/ui/CButton.vue')['default']
    ComplexArrayBuilder: typeof import('./src/components/ui/ComplexArrayBuilder.vue')['default']
    ComponentFormWrapper: typeof import('./src/components/modules/ComponentFormWrapper.vue')['default']
    ComponentLoadSessions: typeof import('./src/components/modules/ComponentLoadSessions.vue')['default']
    ComponentNode: typeof import('./src/components/modules/ComponentNode.vue')['default']
    ComponentQuickEditPanel: typeof import('./src/components/modules/ComponentQuickEditPanel.vue')['default']
    ContextMenu: typeof import('./src/components/ui/ContextMenu.vue')['default']
    COverlay: typeof import('./src/components/ui/COverlay.vue')['default']
    CreateNodeMenu: typeof import('./src/components/modules/CreateNodeMenu.vue')['default']
    CreateObjectDialog: typeof import('./src/components/modules/CreateObjectDialog.vue')['default']
    DialogSettings: typeof import('./src/components/modules/DialogSettings.vue')['default']
    ExplorerPanel: typeof import('./src/components/modules/ExplorerPanel.vue')['default']
    ExplorerRail: typeof import('./src/components/modules/ExplorerRail.vue')['default']
    ExpressionBuilder: typeof import('./src/components/ui/ExpressionBuilder.vue')['default']
    GlobalOverlays: typeof import('./src/components/global/GlobalOverlays.vue')['default']
    GlobalSearch: typeof import('./src/components/modules/GlobalSearch.vue')['default']
    IconRender: typeof import('./src/components/ui/IconRender.vue')['default']
    Logo: typeof import('./src/components/ui/Logo.vue')['default']
    Node: typeof import('./src/components/ui/Node.vue')['default']
    ProjectCard: typeof import('./src/components/modules/ProjectCard.vue')['default']
    Properties: typeof import('./src/components/modules/Properties.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarProjects: typeof import('./src/components/modules/SidebarProjects.vue')['default']
    UserProfileMenu: typeof import('./src/components/modules/UserProfileMenu.vue')['default']
    VPasswordField: typeof import('./src/components/ui/VPasswordField.vue')['default']
  }
}
