/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateAnchor: typeof import('./src/components/elements/CreateAnchor.vue')['default']
    CreateButton: typeof import('./src/components/elements/CreateButton.vue')['default']
    CreateCard: typeof import('./src/components/elements/CreateCard.vue')['default']
    CreateContextMenu: typeof import('./src/components/elements/CreateContextMenu.vue')['default']
    CreateLoading: typeof import('./src/components/elements/CreateLoading.vue')['default']
    CreateLogo: typeof import('./src/components/elements/CreateLogo.vue')['default']
    CreateNode: typeof import('./src/components/elements/CreateNode.vue')['default']
    CreateStepProgress: typeof import('./src/components/elements/CreateStepProgress.vue')['default']
    CreateTextField: typeof import('./src/components/elements/CreateTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
