/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CButton: typeof import('./src/components/ui/CButton.vue')['default']
    CContextMenu: typeof import('./src/components/ui/CContextMenu.vue')['default']
    CGameCard: typeof import('./src/components/ui/CGameCard.vue')['default']
    CLink: typeof import('./src/components/ui/CLink.vue')['default']
    CLoading: typeof import('./src/components/ui/CLoading.vue')['default']
    CLogo: typeof import('./src/components/ui/CLogo.vue')['default']
    CNode: typeof import('./src/components/ui/CNode.vue')['default']
    CPasswordInput: typeof import('./src/components/ui/CPasswordInput.vue')['default']
    CSelect: typeof import('./src/components/ui/CSelect.vue')['default']
    CStepProgress: typeof import('./src/components/ui/CStepProgress.vue')['default']
    CTextField: typeof import('./src/components/ui/CInputText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
