/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./components/base/BaseCard.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseLoading: typeof import('./components/base/BaseLoading.vue')['default']
    CButton: typeof import('./components/ui/CButton.vue')['default']
    CContextMenu: typeof import('./components/ui/CContextMenu.vue')['default']
    CFeaturedGameCard: typeof import('./components/ui/CFeaturedGameCard.vue')['default']
    CGroup: typeof import('./components/ui/CGroup.vue')['default']
    CInputPassword: typeof import('./components/ui/CInputPassword.vue')['default']
    CInputSelect: typeof import('./components/ui/CInputSelect.vue')['default']
    CInputText: typeof import('./components/ui/CInputText.vue')['default']
    CLink: typeof import('./components/ui/CLink.vue')['default']
    CLoading: typeof import('./components/ui/CLoading.vue')['default']
    CLogo: typeof import('./components/ui/CLogo.vue')['default']
    CNode: typeof import('./components/ui/CNode.vue')['default']
    ComponentDialog: typeof import('./components/modules/ComponentDialog.vue')['default']
    ComponentFormWrapper: typeof import('./components/modules/ComponentFormWrapper.vue')['default']
    ComponentGamepad: typeof import('./components/modules/ComponentGamepad.vue')['default']
    ComponentHeader: typeof import('./components/modules/ComponentHeader.vue')['default']
    ComponentLoadSessions: typeof import('./components/modules/ComponentLoadSessions.vue')['default']
    ComponentNode: typeof import('./components/modules/ComponentNode.vue')['default']
    ComponentQuickEditPanel: typeof import('./components/modules/ComponentQuickEditPanel.vue')['default']
    CSelect: typeof import('./components/ui/CSelect.vue')['default']
    CStepProgress: typeof import('./components/ui/CStepProgress.vue')['default']
    CSwitch: typeof import('./components/ui/CSwitch.vue')['default']
    CToggle: typeof import('./components/ui/CToggle.vue')['default']
    DialogMessage: typeof import('./components/dialogs/DialogMessage.vue')['default']
    DialogSettings: typeof import('./components/dialogs/DialogSettings.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
