import {
	Add,
	AtOutline,
	CalculatorOutline,
	CheckmarkCircleOutline,
	ChevronBack,
	ChevronForward,
	Close,
	CloseCircleOutline,
	CodeOutline,
	CreateOutline,
	EllipsisVertical,
	ExtensionPuzzleOutline,
	GridOutline,
	LaptopOutline,
	LockClosedOutline,
	LockOpenOutline,
	LogOutOutline,
	MailOutline,
	PersonCircleOutline,
	PersonOutline,
	Play,
	PlayCircleOutline,
	PlaySkipForwardOutline,
	Repeat,
	ReturnDownBackOutline,
	Search,
	SwapHorizontalOutline,
	Sync,
	TerminalOutline,
	TrashOutline,
} from "@vicons/ionicons5";

import {
	AbcOutlined,
	AddBoxOutlined,
	AltRouteOutlined,
	CallSplitOutlined,
	CloudDoneOutlined,
	CloudOutlined,
	CloudQueueOutlined,
	CloudSyncOutlined,
	CodeOutlined,
	ComputerOutlined,
	FunctionsOutlined,
	HubOutlined,
	SearchOffOutlined,
	SmartphoneOutlined,
	SubdirectoryArrowRightOutlined,
	UnfoldLessOutlined,
	UnfoldMoreOutlined,
} from "@vicons/material";

const iconMap: Record<string, any> = {
	delete: TrashOutline,
	add: Add,
	chevron_right: ChevronForward,
	chevron_left: ChevronBack,
	edit: CreateOutline,
	lock: LockClosedOutline,
	lock_open: LockOpenOutline,
	devices: LaptopOutline,
	logout: LogOutOutline,
	unfold_less: UnfoldLessOutlined,
	unfold_more: UnfoldMoreOutlined,
	interests: ExtensionPuzzleOutline,
	search: Search,
	search_off: SearchOffOutlined,
	terminal: TerminalOutline,
	more_vert: EllipsisVertical,
	grid_view: GridOutline,
	close: Close,
	data_object: CodeOutlined,
	alternate_email: AtOutline,
	face: PersonOutline,
	mail_outline: MailOutline,
	play_arrow: Play,
	code: CodeOutline,
	smartphone: SmartphoneOutlined,
	computer: ComputerOutlined,
	assignment_ind: PersonCircleOutline,
	check_circle: CheckmarkCircleOutline,
	hub: HubOutlined,
	functions: FunctionsOutlined,
	function: CodeOutline,
	play_circle: PlayCircleOutline,
	keyboard_return: ReturnDownBackOutline,
	alt_route: AltRouteOutlined,
	call_split: CallSplitOutlined,
	repeat: Repeat,
	sync: Sync,
	cancel: CloseCircleOutline,
	skip_next: PlaySkipForwardOutline,
	switch_access_shortcut: SwapHorizontalOutline,
	subdirectory_arrow_right: SubdirectoryArrowRightOutlined,
	abc: AbcOutlined,
	add_box: AddBoxOutlined,
	calculate: CalculatorOutline,
	cloud: CloudOutlined,
	cloud_sync: CloudSyncOutlined,
	cloud_alert: CloudQueueOutlined,
	cloud_done: CloudDoneOutlined,
};

export function getIconComponent(name: string | undefined | null) {
	if (!name) return null;
	return iconMap[name.trim()] || null;
}
